baseURL = "http://vintergarder.dk/"
languageCode = "da-dk"
title = "Vintergarder"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "da"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-88778140-1"
enableRobotsTXT = true
disqusShortname = "vintergarder-dk"

[menu]
	[[menu.main]]
	identifier = "home"
	name = "Forside"
	url = "/"
	weight = 1

	[[menu.main]]
	identifier = "about"
	name = "Baggrund"
	url = "/about"
	weight = 2

	[[menu.main]]
	identifier = "posts"
	name = "Dagbog"
	url = "/posts"
	weight = 3

	[[menu.main]]
	identifier = "rex"
	name = "REX-turen"
	url = "/rex"
	weight = 4

	[[menu.main]]
	identifier = "blaa_fest"
	name = "Blå fest"
	url = "/blaa_fest"
	weight = 5

	[[menu.main]]
	identifier = "more"
	name = "Mere"
	url = "/more"
	weight = 6

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/graphics/pro_rege_et_grege.png"
  description = "Den kongelige livgarde."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/design/header.jpg"
  recent_posts_number = 5
  custom_css = ["css/custom.css"]